# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weatherPaca.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(441, 522)
        MainWindow.setMaximumSize(QtCore.QSize(441, 522))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 160, 421, 351))
        self.groupBox.setObjectName("groupBox")
        self.pbActualiser = QtWidgets.QPushButton(self.groupBox)
        self.pbActualiser.setGeometry(QtCore.QRect(10, 30, 181, 23))
        self.pbActualiser.setObjectName("pbActualiser")
        self.lbDatePrevisions = QtWidgets.QLabel(self.groupBox)
        self.lbDatePrevisions.setGeometry(QtCore.QRect(10, 60, 211, 16))
        self.lbDatePrevisions.setText("")
        self.lbDatePrevisions.setObjectName("lbDatePrevisions")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 80, 231, 251))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.lcdTemperature = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdTemperature.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdTemperature.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdTemperature.setLineWidth(1)
        self.lcdTemperature.setDigitCount(5)
        self.lcdTemperature.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdTemperature.setProperty("value", 0.0)
        self.lcdTemperature.setObjectName("lcdTemperature")
        self.gridLayout.addWidget(self.lcdTemperature, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.lcdHumidity = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdHumidity.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdHumidity.setObjectName("lcdHumidity")
        self.gridLayout.addWidget(self.lcdHumidity, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.lcdPression = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdPression.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdPression.setObjectName("lcdPression")
        self.gridLayout.addWidget(self.lcdPression, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)
        self.lcdVitesseVent = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdVitesseVent.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdVitesseVent.setObjectName("lcdVitesseVent")
        self.gridLayout.addWidget(self.lcdVitesseVent, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 4, 0, 1, 1)
        self.lcdDirectionVent = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdDirectionVent.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdDirectionVent.setObjectName("lcdDirectionVent")
        self.gridLayout.addWidget(self.lcdDirectionVent, 4, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 4, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 5, 0, 1, 1)
        self.lcdNuage = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdNuage.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNuage.setObjectName("lcdNuage")
        self.gridLayout.addWidget(self.lcdNuage, 5, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 5, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 6, 0, 1, 1)
        self.lcdPluie = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdPluie.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdPluie.setObjectName("lcdPluie")
        self.gridLayout.addWidget(self.lcdPluie, 6, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 6, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 7, 0, 1, 1)
        self.lcdNeige = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdNeige.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNeige.setObjectName("lcdNeige")
        self.gridLayout.addWidget(self.lcdNeige, 7, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 7, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 421, 165))
        self.groupBox_2.setObjectName("groupBox_2")
        self.cbDepartements = QtWidgets.QComboBox(self.groupBox_2)
        self.cbDepartements.setGeometry(QtCore.QRect(110, 30, 261, 23))
        self.cbDepartements.setAutoFillBackground(True)
        self.cbDepartements.setObjectName("cbDepartements")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 60, 34, 16))
        self.label.setObjectName("label")
        self.lbPrevisionsVille = QtWidgets.QLabel(self.groupBox_2)
        self.lbPrevisionsVille.setGeometry(QtCore.QRect(10, 110, 411, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbPrevisionsVille.setFont(font)
        self.lbPrevisionsVille.setObjectName("lbPrevisionsVille")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 91, 21))
        self.label_2.setObjectName("label_2")
        self.cbVilles = QtWidgets.QComboBox(self.groupBox_2)
        self.cbVilles.setEnabled(True)
        self.cbVilles.setGeometry(QtCore.QRect(110, 60, 261, 23))
        self.cbVilles.setAutoFillBackground(True)
        self.cbVilles.setObjectName("cbVilles")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pbActualiser.clicked.connect(MainWindow.previsions)
        self.cbVilles.currentTextChanged['QString'].connect(MainWindow.show_city)
        self.cbDepartements.currentTextChanged['QString'].connect(MainWindow.fill_cb_city)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Weather Paca"))
        self.groupBox.setTitle(_translate("MainWindow", "Météo"))
        self.pbActualiser.setText(_translate("MainWindow", "Actualiser"))
        self.label_3.setText(_translate("MainWindow", "Température :"))
        self.label_5.setText(_translate("MainWindow", "°C"))
        self.label_4.setText(_translate("MainWindow", "Humidité : "))
        self.label_6.setText(_translate("MainWindow", "%"))
        self.label_7.setText(_translate("MainWindow", "Pression"))
        self.label_8.setText(_translate("MainWindow", "hPa"))
        self.label_9.setText(_translate("MainWindow", "Vitesse du vent :"))
        self.label_10.setText(_translate("MainWindow", "km/h"))
        self.label_17.setText(_translate("MainWindow", "Direction vent :"))
        self.label_18.setText(_translate("MainWindow", "°"))
        self.label_11.setText(_translate("MainWindow", "Nuages :"))
        self.label_12.setText(_translate("MainWindow", "%"))
        self.label_13.setText(_translate("MainWindow", "Pluie :"))
        self.label_14.setText(_translate("MainWindow", "mm"))
        self.label_15.setText(_translate("MainWindow", "Neige :"))
        self.label_16.setText(_translate("MainWindow", "mm"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Localisation"))
        self.label.setText(_translate("MainWindow", "Ville :"))
        self.lbPrevisionsVille.setText(_translate("MainWindow", "Prévisions pour :"))
        self.label_2.setText(_translate("MainWindow", "Département :"))


